const menu = [{
        id: 1,
        name: "Maggiee",
        price: 150,
        catagory: "Breakfast",
        about: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil saepe cupiditate, asperiores pariatur obcaecati tempora?",
        img: "https://assets.gqindia.com/photos/5e7b607a0b0ce700084bd587/master/w_1440%2cc_limit/Chilli%20Cheese%20Maggi%20.jpg",
    },
    {
        id: 2,
        name: "Curd",
        price: 50,
        catagory: "Breakfast",
        about: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil saepe cupiditate, asperiores pariatur obcaecati tempora?",
        img: "https://th.bing.com/th/id/OIP.51zRVfg8H4az2huBdH1LFgHaE8?rs=1&pid=ImgDetMain",
    },
    {
        id: 3,
        name: "Bread mink",
        price: 100,
        catagory: "Breakfast",
        about: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil saepe cupiditate, asperiores pariatur obcaecati tempora?",
        img: "https://static.vecteezy.com/system/resources/previews/000/846/165/large_2x/milk-and-bread-photo.jpg",
    },
    {
        id: 4,
        name: "meal(veg)",
        price: 70,
        catagory: "lunch",
        about: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil saepe cupiditate, asperiores pariatur obcaecati tempora?",
        img: "https://cdn.apartmenttherapy.info/image/fetch/f_auto,q_auto:eco,w_1460/https://storage.googleapis.com/gen-atmedia/3/2017/09/3df14d9de6e476dd0457478ce74f007a1262387c.jpeg",
    },
    {
        id: 5,
        name: "meal(non-veg)",
        price: 100,
        catagory: "lunch",
        about: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil saepe cupiditate, asperiores pariatur obcaecati tempora?",
        img: "https://www.archanaskitchen.com/images/archanaskitchen/0-Contest/recipe-contest-share-the-best-non-veg-recipe-from-your-kitchen.jpg",
    },
    {
        id: 6,
        name: "Biriyani",
        price: 120,
        catagory: "lunch",
        about: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil saepe cupiditate, asperiores pariatur obcaecati tempora?",
        img: "https://www.thespruceeats.com/thmb/SalyKjzBU-K1Bv-FTFWnbd6ckjY=/2121x1414/filters:fill(auto,1)/GettyImages-639704020-5c4a63ecc9e77c00017bfebf.jpg",
    },
    {
        id: 7,
        name: "Mutton",
        price: 170,
        catagory: "lunch",
        about: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil saepe cupiditate, asperiores pariatur obcaecati tempora?",
        img: "https://th.bing.com/th/id/OIP.lEzRybhAQtUHeNyzYCLxVgHaE8?rs=1&pid=ImgDetMain",
    },
    {
        id: 8,
        name: "Chatt",
        price: 50,
        catagory: "starter",
        about: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil saepe cupiditate, asperiores pariatur obcaecati tempora?",
        img: "https://img-global.cpcdn.com/recipes/bb7a32e167891c7b/680x482cq70/chatt-patti-tikki-recipe-main-photo.jpg",
    },
    {
        id: 9,
        name: "Roti curry",
        price: 40,
        catagory: "dinner",
        about: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil saepe cupiditate, asperiores pariatur obcaecati tempora?",
        img: "https://th.bing.com/th/id/OIP.1IK_-NEOHWNJ8Cb9dvrJQwHaFj?rs=1&pid=ImgDetMain",
    },
    {
        id: 10,
        name: "Sada tadaka",
        price: 50,
        catagory: "dinner",
        about: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil saepe cupiditate, asperiores pariatur obcaecati tempora?",
        img: "https://th.bing.com/th/id/OIP.d0r8Tn6d7kI8L10O0YlgGAHaE8?rs=1&pid=ImgDetMain",
    },
];

export default menu;